[master] Ignore not exist error when detaching device
openmainframeproject/python-zvm-sdk pull request #338
Opened 2020-08-19 01:22 UTC by changzhi1990

Ignore the NotExistException when detaching a FCP device.
Because in some unexcepted cases, the connections of a FCP
device might be 0, at those cases, the volume can't detach
anymore. So we should handle this exception and set its
connections to 0.

2020-08-20 07:14 UTC, dongyanyang requested changes

2020-08-20 07:14 UTC, dongyanyang commented on zvmsdk/volumeop.py
>              LOG.error(errmsg)
Don't log this as error at this time.
put this log to line 716.

2020-08-20 07:14 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            if err.results['rc'] == 404 and err.results['rs'] == 8:
You should also handle the following scenario:
```
[root@112-cmp-ydy ~]# /bin/smcli Image_Device_Undedicate --addRCheader -T iaas00bb -v 1a14
8 204 8 (details) ULGSMC5204E Image device does not exist
  API issued : Image_Device_Undedicate
Deleting dedicated device from iaas00bb's active configuration...
Failed
  Return Code: 204
  Reason Code: 8
  Description: ULGSMC5204E Image device does not exist
  API issued : Image_Device_Undedicate
[root@112-cmp-ydy ~]#
```

2020-08-24 05:51 UTC, changzhi1990 commented
Ran 646 tests in 1.045s

OK (skipped=3)
py36 run-test: commands[1] | python -m unittest discover -v -s /root/changzhi/python-zvm-sdk/smtLayer/tests/unit
test_getDiskPoolSpace3390 (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace3390Unknown (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace3390UnknownWithFlag (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace9336 (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace9336Unknown (test_getHost.SMTGetHostTestCase) ... ok
test_getDiskPoolSpace9336UnknownWithFlag (test_getHost.SMTGetHostTestCase) ... ok
test_getReservedMemSize (test_makeVM.SMTMakeVMTestCase) ... ok
test_getReservedMemSize_equal_size (test_makeVM.SMTMakeVMTestCase) ... ok
test_getReservedMemSize_gap_G (test_makeVM.SMTMakeVMTestCase) ... ok
test_getReservedMemSize_invalid_suffix (test_makeVM.SMTMakeVMTestCase) ... ok
test_getReservedMemSize_max_less_than_initial (test_makeVM.SMTMakeVMTestCase) ... ok
test_getVM_directory_py3 (test_vmUtils.SMTvmUtilsTestCase) ... ok

----------------------------------------------------------------------
Ran 12 tests in 0.004s

OK
______________________________________________________________ summary ______________________________________________________________
  py36: commands succeeded
  congratulations :)


[root@rhel82-com python-zvm-sdk]# tox -epep8
pep8 develop-inst-noop: /root/changzhi/python-zvm-sdk
pep8 installed: attrs==20.1.0,certifi==2020.6.20,chardet==3.0.4,flake8==3.8.3,idna==2.10,importlib-metadata==1.7.0,importlib-resources==3.0.0,jsonschema==3.2.0,mccabe==0.6.1,netaddr==0.8.0,pycodestyle==2.6.0,pyflakes==2.2.0,PyJWT==1.7.1,pyrsistent==0.16.0,PyYAML==5.3.1,repoze.lru==0.7,requests==2.24.0,Routes==2.4.1,six==1.15.0,urllib3==1.25.10,WebOb==1.8.6,zipp==3.1.0,-e git+https://github.com/openmainframeproject/python-zvm-sdk.git@573a9b602211acc321f1b994a31146e494237ec9#egg=zVMCloudConnector
pep8 run-test-pre: PYTHONHASHSEED='1141681791'
pep8 run-test: commands[0] | flake8
pep8 run-test: commands[1] | flake8 /root/changzhi/python-zvm-sdk/scripts/sdkserver
______________________________________________________________ summary ______________________________________________________________
  pep8: commands succeeded
  congratulations :)

2020-08-24 05:52 UTC, dongyanyang approved these changes

2020-08-24 05:52 UTC, dongyanyang commented
@bjhuangr @jichenjc pls help to review, thanks

2020-08-24 06:01 UTC, jichenjc commented
lgtm

2020-08-24 06:06 UTC, bjhuangr commented on zvmsdk/volumeop.py
> +            if rc == 404 or rc == 204 and rs == 8:
`or` first or `and` first?
Suggest to add parentheses to make your code more readable.

2020-08-24 06:08 UTC, merged