[master]raise exception when IUCV is unauthorized
openmainframeproject/python-zvm-sdk pull request #359
Opened 2020-09-22 06:06 UTC by SharpRazor

raise exception when IUCV is unauthorized.

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2020-09-22 06:09 UTC, jichenjc commented
please open a bug to indicate the reason for such PR

2020-09-22 06:23 UTC, SharpRazor commented
> please open a bug to indicate the reason for such PR

it is not proper to paste issue id here, this PR is for issue 3835

2020-09-22 07:43 UTC, dongyanyang commented
Just checked code. is_reachable is only used by volume attach/detach. 
Instead of fix is_reachable in this way, I would prefer to change the call of is_reachable to the smtclient: execute_cmd(userid, 'pwd'), refering to the way of guest_capture:

```
 # Make sure the iucv channel is ready for communication on source vm
        try:
            self.execute_cmd(userid, 'pwd')
        except exception.SDKSMTRequestFailed as err:
            msg = ('Failed to check iucv status on capture source vm '
                   '%(vm)s with error %(err)s' % {'vm': userid,
                                        'err': err.results['response'][0]})
            LOG.error(msg)
            raise exception.SDKGuestOperationError(rs=5, userid=userid,
                                                   msg=msg)
```

2020-09-24 05:41 UTC, SharpRazor commented
@dongyanyang new version committed, pls review, thanks!

2020-09-24 06:23 UTC, dongyanyang requested changes

2020-09-24 06:23 UTC, dongyanyang commented on smtLayer/getVM.py
> +       rs - 0: not reachable, 1: reachable, 2: unreachable but can continue
pls revert the isreachable related change, don't change the logic as we now would not use this function.

2020-09-24 06:23 UTC, dongyanyang commented on zvmsdk/smtclient.py
> +        elif results['rs'] == 0:
ditto, need to be reverted.

2020-09-24 06:23 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                raise exception.SDKGuestOperationError(rs=5, userid=assigner_id,
Volume related exception, should not be GuestOperationError

And for all the rs values, they should have definitions in returncode.py

```
# Volume Operation failed
    'volume': [{'overallRC': 300, 'modID': ModRCs['volume'], 'rc': 300},
               {1: "Database operation failed, error: %(msg)s",
                3: "Volume %(vol)s has already been attached on instance "
                   "%(inst)s",
                4: "Volume %(vol)s is not attached on instance %(inst)s",
                5: "Refresh bootmap fails, error code: %(errcode)s and "
                   "reason: %(errmsg)s",
                },
               "Operation on Volume failed"
               ],
```

2020-09-24 06:23 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            if 'unauthorize' in err.format_message().lower():
unauthorize -> UNAUTHORIZED_ERROR
All IUCV unauthorized error would use this prefix.

2020-09-24 06:23 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        self.check_IUCV_is_ready(assigner_id)
check_IUCV_is_ready should return true or false to indicate whether the VM is in active or inactive state.

2020-09-24 06:23 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        if need_restart:
not only check need_restart, also vm active or not.

2020-09-24 06:23 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        if need_restart:
ditto

2020-09-24 06:49 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        self.check_IUCV_is_ready(assigner_id)
if check_IUCV_is_ready raise exception, the code can not continue, is it necessary to return values?

2020-09-24 07:14 UTC, SharpRazor commented on smtLayer/getVM.py
> +       rs - 0: not reachable, 1: reachable, 2: unreachable but can continue
I think no need to revert this, it didn't impact current codes and it is really a bug that didn't raise an exception when unauthorized.

2020-09-24 07:32 UTC, bjhuangr commented on zvmsdk/volumeop.py
> +                raise exception.SDKGuestOperationError(rs=5, userid=assigner_id,
If any error message changes involved, don't forget to run tox to re-generate errorcodemsg.rst, and submit the change together within this same pull request.

2020-09-24 07:32 UTC, bjhuangr commented on zvmsdk/smtclient.py
> +        elif results['rs'] == 0:
can we always assume  `results['rs'] == 0` because of unauthorized? any other reason? e.g. iucv server is down, guest in shutdown state ..

2020-09-24 07:32 UTC, bjhuangr commented on smtLayer/getVM.py
> +       rs - 0: not reachable, 1: reachable, 2: unreachable but can continue
It is acceptable to me to add more reason codes, as this is internal invoke only. Make sure all the places that call this method be handled correctly.

2020-09-24 07:39 UTC, SharpRazor commented on smtLayer/getVM.py
> +       rs - 0: not reachable, 1: reachable, 2: unreachable but can continue
follow dongyan's comments, after revert, so there is no need to full regression about changes of is_reachable.

2020-09-24 07:41 UTC, SharpRazor commented on zvmsdk/smtclient.py
> +        elif results['rs'] == 0:
the rc differs between unauthorized and guest is down.
I am only sure unauthorization will make it to 0, but not sure all cases, so I revert it.

2020-09-24 07:42 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                raise exception.SDKGuestOperationError(rs=5, userid=assigner_id,
go advice , I didn't know that.

2020-09-24 07:43 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            if 'unauthorize' in err.format_message().lower():
done.

2020-09-24 10:09 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        if need_restart:
done

2020-09-24 10:09 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        if need_restart:
done

2020-09-25 04:37 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                msg = ('Failed to connect iucv on VM %(vm)s with error '
I think it is confusing to have such debug info in log, it is normal to enter this 'else' representing vm is in off state.
better to 
1. remove iucv word
2. append msg: assuming vm is in OFF state.

2020-09-25 04:37 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                msg = ('IUCV failed to get authorization from VM %(vm)s with '
move this part to the new added return code in returncode.py

2020-09-25 04:37 UTC, dongyanyang commented on zvmsdk/returncode.py
> +                6: "Volume attached on instance %(userid)s failed with reason "
this msg will be used not only by attach, detach will also use it.
so suggest to change the msg to:

 > IUCV failed to get authorization from VM %(vm)s with error %(err)s

2020-09-25 04:45 UTC, SharpRazor commented on zvmsdk/returncode.py
> +                6: "Volume attached on instance %(userid)s failed with reason "
right.

2020-09-25 04:54 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                msg = ('Failed to connect iucv on VM %(vm)s with error '
done

2020-09-25 04:54 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                msg = ('IUCV failed to get authorization from VM %(vm)s with '
done.

2020-09-25 04:55 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                msg = ('IUCV failed to get authorization from VM %(vm)s with '
the LOG.error need this msg, so I copy this to returncode.py

2020-09-25 04:57 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                msg = ('IUCV failed to get authorization from VM %(vm)s with '
althogh the error messages may looks duplicated.

2020-09-25 07:11 UTC, dongyanyang commented on doc/source/errcode.csv
> +300;30;300;6;Volume attached on instance %(userid)s failed with reason %(msg)s
you need to rerun tox -edocs to update the doc

2020-09-25 07:11 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                msg = ('IUCV failed to get authorization from VM %(vm)s with '
no, you can use the msg for LOG, but when pass to the exception, just use the err.results['response'][0], then no duplication.

2020-09-25 07:32 UTC, SharpRazor commented on doc/source/errcode.csv
> +300;30;300;6;Volume attached on instance %(userid)s failed with reason %(msg)s
oh, forgot, done

2020-09-25 07:32 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                msg = ('IUCV failed to get authorization from VM %(vm)s with '
yes, right.

2020-09-25 07:36 UTC, dongyanyang approved these changes
LGTM

2020-09-25 07:37 UTC, dongyanyang commented
@jichenjc we can remove the HOLD label now

2020-09-25 08:04 UTC, merged